plugins:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Max: 35

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'

RSpec/MultipleExpectations:
  Max: 12

RSpec/MultipleMemoizedHelpers:
  Max: 7

RSpec/NestedGroups:
  Max: 5

RSpec/ExampleLength:
  Enabled: false